Anakural: derle calistir

derle:
	g++ -I ./include/ -o ./lib/BinarySearchTree.o -c ./src/BinarySearchTree.cpp
	g++ -I ./include/ -o ./lib/Dugum.o -c ./src/Dugum.cpp
	g++ -I ./include/ -o ./lib/LinkedList.o -c ./src/LinkedList.cpp
	g++ -I ./include/ -o ./lib/ListeDugum.o -c ./src/ListeDugum.cpp	
	g++ -I ./include/ -o ./bin/Main ./lib/BinarySearchTree.o ./lib/Dugum.o ./lib/LinkedList.o ./lib/ListeDugum.o ./src/main.cpp

calistir:
	./bin/Main.exe
